site_name: "FLAD Entrega 2: Cores"

site_dir: docs

theme:
  name: material
  palette:
    scheme: default
    primary: '#FF0000'   # red hex
    accent: '#00FF00'    # green hex

docs_dir: src_docs
extra_css:
  - custom/style.css
