site_name: Entrega 2

extra_css:
  - styles/style.css
  
site_name: Moodle
extra_css:
  - custom/style.css
  
theme:
  name: material
  palette:
    - scheme: default
      primary: red
      accent: pink
