docs_dir: src_docs
site_name: FLAD Core Documentation  
site_dir: docs           

extra_css:
  - styles/style.css
  
site_name: Moodle
extra_css:
  - custom/style.css
  
theme:
  name: material
  palette:
    - scheme: default
      primary: red
      accent: pink

extra_css:
  - css/custom.css  
