repo_name: FLAD entrega 2

site_name: Moodle
extra_css:
  - style.css
  
theme:
  name: material
  palette:
    - scheme: default
      primary: red
      accent: pink

extra_css:
  - styles/style.css
