site_name: FLAD Entrega 2: Cores
docs_dir: src_docs
site_dir: docs           
  
  
theme:
  name: material
  palette:
    - scheme: default
      primary: red
      accent: green

extra_css:
  - custom/style.css  
