name: Build and Commit MkDocs Site

on:
  push:
    branches:
      - main

permissions:
  contents: write  # needed to push changes

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install MkDocs
        run: |
          pip install mkdocs mkdocs-material

      - name: Build site folder (docs/)
        run: |
          mkdocs build --clean  # MkDocs reads site_dir from config (docs/)

      - name: Commit generated docs folder
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs
          git commit -m "Auto-build site in docs folder" || echo "Nothing to commit"
          git push
